# This file purpose is to configure pytest settings
# This file solved the issues of not finding the import modules I had before
[pytest]
# tell pytest to look for tests in the 'tests' directory
testpaths = tests 
# include the current directory in the Python path
pythonpath = . 
# ensure local modules are imported first, avoids collusion for same named files
addopts = --import-mode=prepend 
